name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  gitleaks:
    uses: rewanthtammana/centralized-workflows/.github/workflows/gitleaks.yml@main
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.17.0]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm ci
    - run: npm run build --if-present

